# Generated by Django 5.1.6 on 2025-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='bimage',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
