# Generated by Django 5.1.6 on 2025-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0005_category_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(null=True, upload_to='media')),
                ('p_code', models.IntegerField(null=True)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('p_price', models.IntegerField(null=True)),
                ('total_amo', models.IntegerField(null=True)),
                ('p_brand', models.CharField(max_length=45, null=True)),
                ('p_category', models.CharField(max_length=35, null=True)),
                ('p_date', models.DateTimeField(null=True)),
                ('up_date', models.DateTimeField(null=True)),
                ('op_stock', models.IntegerField(null=True)),
                ('cp_stock', models.IntegerField(null=True)),
                ('p_status', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
