# Generated by Django 5.1.6 on 2025-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='up_date',
            field=models.DateField(null=True),
        ),
    ]
