# Generated by Django 5.1.6 on 2025-04-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
