# Generated by Django 5.1.6 on 2025-04-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
