# Generated by Django 5.1.6 on 2025-04-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0014_product_p_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_tax',
        ),
    ]
