# Generated by Django 5.1.6 on 2025-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0015_remove_product_p_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phn_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
    ]
