# Generated by Django 5.1.6 on 2025-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
