# Generated by Django 5.1.6 on 2025-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0017_order_order_id_order_payment_id_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_id', models.IntegerField(null=True)),
                ('dp_pic', models.ImageField(null=True, upload_to='media')),
                ('dp_name', models.CharField(max_length=30, null=True)),
                ('dp_email', models.EmailField(max_length=254)),
                ('dp_number', models.IntegerField(null=True)),
                ('dp_uname', models.CharField(max_length=10, null=True)),
                ('dp_password', models.CharField(max_length=10, null=True)),
                ('dp_date', models.DateField(null=True)),
            ],
        ),
    ]
