# Generated by Django 5.1.6 on 2025-05-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0018_deliveryp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=255)),
                ('c_address', models.TextField()),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('d_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veg.deliveryp')),
            ],
        ),
    ]
