# Generated by Django 5.1.6 on 2025-05-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0019_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
