# Generated by Django 5.1.6 on 2025-05-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0020_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veg.deliveryp')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veg.order')),
            ],
        ),
    ]
