# Generated by Django 5.1.6 on 2025-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0022_oder_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
