# Generated by Django 5.1.6 on 2025-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0023_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20, null=True)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_phone', models.IntegerField(null=True)),
                ('e_question', models.TextField(null=True)),
            ],
        ),
    ]
